# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2aaf85327ea63c54b963abe22f3120742c3104c73361bff17076156e2db51c534c7587d9dc7f372ce3f9b44cd81c458616e2549367a596e34d4b4fdce5bb1e2

test:
  secret_key_base: 5aa4e43eef3dbc1ff6589773a1c04b97e099336ee85b390a6c557c88f4a090fe5d1349bf2457d17d708612f513e56b70fd3d406b04c7dcd24b6f3865ebaa82f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
